---
# handlers file for NIST800-171_Ubuntu20
- name: dconf_update
  command: dconf update

- name: ssh_restart
  service:
    name: sshd
    state: restarted

- name: auditd_restart
  service:
    name: auditd
    state: restarted
    use: service